name: Go Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.20.4'

      - name: Build
        run: |
           CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -tags musl -o go4v2fly .
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: go4v2fly
          path: ./go4v2fly

      - run: ls
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: hoi4tech/go4v2fly:latest
